module.exports = Object.freeze({
    STATE_NEW: 'new',
    STATE_STARTED: 'started',
    STATE_PAUSED: 'paused',
    STATE_END: 'end',
    JOIN_STATUS_FULL: 1,
    JOIN_STATUS_NOT_EXISTS: 2,
    JOIN_STATUS_OK: 3,
    SPY: 'Špión',
    SECONDS_TO_END: 480,
    MAX_PLAYERS: 8,
    CARD: {
        'Hotel': [
            'Recepční',
            'Barman',
            'Pokojská',
            'Ředitel hotelu',
            'Pikolík',
            'Host',
            'Ochranka'],
        'Letadlo': [
            'Pilot',
            'Druhý pilot',
            'Pasažér v ekonomické třídě',
            'Letecký mechanik',
            'Pasažér v byzbys třídě',
            'Letuška',
            'Černý pasažér'],
        'Autoservis': [
            'Vedoucí',
            'Automechanik',
            'Cyklista',
            'Zaměstnanec reklamačního oddělení',
            'Obsluha automyčky',
            'Autotronik'],
        'Univerzita': [
            'Studijní referentka',
            'Student',
            'Doktorand',
            'Profesor',
            'Zahraniční student',
            'Děkan',
            'Rektor'],
        'Pláž': [
            'Šmírák',
            'Fotograf s opičkou',
            'Vodní lyžař',
            'Plavčík',
            'Prodavač zmrzliny',
            'Delegát cestovní kanceláře',
            'Rekreant',],
        'Cirkus': [
            'Artista',
            'Klaun',
            'Žonglér',
            'Kouzelník',
            'Návštevník',
            'Vrhač nožů',
            'Krotiel šelem',],
        'Vlak': [
            'Strojvedoucí',
            'Vlakový lupič',
            'Kuchař v jídelním voze',
            'Průvodčí',
            'Celník',
            'Topič',
            'Pasažér',],
        'Ambasáda': [
            'Konzul',
            'Šofér limuzíny',
            'Politický uprchlík',
            'Diplomat',
            'Velvyslanec',
            'Ochranka',
            'Asistenka',],
        'Filmové studio': [
            'Režisér',
            'Zvukař',
            'Začínající herec',
            'Filmová hvězda',
            'Kameraman',
            'Kostymér',
            'Kaskadér',],
        'Zabavní park': [
            'Návštěvník',
            'Prodavač cukrovinek',
            'Mechanik horské dráhy',
            'Dítě',
            'Klaun',
            'Obsluha strašidelného hradu',
            'Vousatá žena',],
        'Firemní večírek': [
            'Nezvaný host',
            'Asistenka',
            'Manažer',
            'Recepční',
            'Účetní',
            'Moderátor',
            'Šéf',],
        'Katedrála': [
            'Varhaník',
            'Turista',
            'Kněz',
            'Hříšník',
            'Kostelník',
            'Žebrák',
            'Zvoník',],
        'Škola': [
            'Šprt',
            'Školník',
            'Telocvikář',
            'Prvňák',
            'Třídní učitelka',
            'Zástupce ředitele',
            'Ředitel',],
        'Restaurace': [
            'Gurmán',
            'Šéfkuchář',
            'Čišník',
            'Vyhazovač',
            'Host',
            'Vedoucí',
            'Hudebník',],
        'Supermarket': [
            'Pokladní',
            'Hlídač',
            'Zákazník',
            'Řezník',
            'Kapsář',
            'Dodavatel',
            'Uklízečka',],
        'Policejní stanice': [
            'Novinář',
            'Vedoucí forenzní laboratoře',
            'Strážník',
            'Obviněný',
            'Žalobce',
            'Obhájce',
            'Detektiv',],
        'Polární stanice': [
            'Velitel exppedice',
            'Radista',
            'Psovod',
            'Meteorolog',
            'Biolog',
            'Lékař',
            'Eskymák',],
        'Pirátská loď': [
            'Zbouřec v řetězech',
            'Otrok',
            'Lodní kuchař',
            'Dělostřelec',
            'Plavčík',
            'Mořský vlk',
            'Kapitán',],
        'Banka': [
            'Vedoucí pobočky',
            'Řidič obrněného vozidla',
            'Pokladní na přepážce',
            'Ostraha',
            'Bankovní lupič',
            'Finační poradce',
            'Zákazník',],
        'Ponorka': [
            'Torpédometčík',
            'Kapitán ponorky',
            'Navigátor',
            'Opeátor sonarů',
            'Radista',
            'Námořník',
            'Mechanik',],
        'Divadlo': [
            'Režisér',
            'Herec',
            'Kulisák',
            'Nápověda',
            'Uvaděč',
            'Divák',
            'Šatnářka',],
        'Zaoceánský parník': [
            'Plavčík',
            'Radista',
            'Bohatá vdova',
            'Stevard',
            'Sňatkový podvodník',
            'Barman',
            'Lodní kapitán',],
        'Zoo': [
            'Ředitel',
            'Údržbář',
            'Prodavač vstupenek',
            'Ošetřovatel zvěře',
            'Dítě',
            'Veterinář',
            'Návštěvník',],
        'Maškarní bál': [
            'Tanečník v masce',
            'Fotograf',
            'Muzikant',
            'Reportér',
            'Kostymér',
            'Celebrita v masce',
            'Čišník',],
        'Taneční klub': [
            'Opilec',
            'Modelka',
            'Vyhazovač',
            'DJ',
            'Barman',
            'Záletník',
            'Tanečnice',],
        'Vojenská základna': [
            'Plukovník',
            'Stráž',
            'Vojín',
            'Zásobovací důstojník',
            'Dezertér',
            'Poddůstojník',
            'Zdravotník',],
        'Kasíno': [
            'Krupiér',
            'Falešný hráč',
            'Šéf ochranky',
            'Vyhazovač',
            'Barman',
            'Manažer',
            'Gamblér',],
        'Vesmírná stanice': [
            'Mimozemšťan',
            'Doktor',
            'Vesmírný turista', // tohle tady nechci
            'Věděc',
            'Mechanik',
            'Pilot',
            'Velitel vesmírné mise',],
        'Nemocnice': [
            'Patolog',
            'Student medicíny',
            'Pacient',
            'Zdravotní sestra',
            'Chirurg',
            'Internista',
            'Primář',],
        'Wellness': [
            'Zákaznice',
            'Výživová poradkyně',
            'Recepční',
            'Vizážistka',
            'Manikérka',
            'Masér',
            'Kosmetička',],
        'Křížová výprava': [
            'Žebravý mnich',
            'Zajatý sracén',
            'Sluha',
            'Biskup',
            'Panoš',
            'Lukostřelec',
            'Rytíř',
        ],
    }
});

